1.Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations




Ans. NumPy has become necessary for scientific computing and data analysis and it is build by "C" language due to its powerful array structure, speed, mathematical,compatibility and manipulate data easiest ways with other scientific libraries, transforming Python into a high-performance language for numerical computation.Python by itself it works fast numerical operations on large datasets, primarily due to the nature of Python native data types and its interpreted nature. its providing fast execution and reducing code complecity.


2.Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?




Ans.The np.mean() and np.average() functions in NumPy both used to compute the average of an array, but they differ in functionality and use cases
1. np.mean() is simpler and suitable for unweighted data.
2. np.average() is more flexible, allowing both weighted and unweighted averages


In [ ]:
import numpy as np


In [ ]:
data = np.array([1, 2, 3, 4, 5])
weights = np.array([1, 2, 3, 4, 5])


In [ ]:
s = np.mean(data)
print("Mean:", s)

Mean: 3.0


In [ ]:
h = np.average(data)
print("Average (no weights):", h)

Average (no weights): 3.0


In [ ]:
a= np.average(data, weights=weights)
print("Weighted Average:",a)


Weighted Average: 3.6666666666666665


3.Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
arrays.


Ans.In NumPy, you can reverse an array along different axes using slicing

1d array-- Simply slice the array with [::-1] to reverse order of elements
2d array -- Use slicing along specific axes to reverse rows or columns

In [ ]:
array_1d = np.array([1, 2, 3, 4, 5])


In [ ]:
array_1d

array([1, 2, 3, 4, 5])

In [ ]:
rever_1d = array_1d[::-1]
print("1D reversed:", rever_1d)

1D reversed: [5 4 3 2 1]


In [ ]:
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [ ]:
array_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
reversed_rows = array_2d[::-1, :]
print("2D Array with Rows Reversed:\n", reversed_rows)


2D Array with Rows Reversed:
 [[7 8 9]
 [4 5 6]
 [1 2 3]]


In [ ]:
reversed_columns = array_2d[:, ::-1]
print("2D Array with Columns Reversed:\n", reversed_columns)


2D Array with Columns Reversed:
 [[3 2 1]
 [6 5 4]
 [9 8 7]]


4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance




Ans.we can use the .dtype attribute To determine the data type of elements in a NumPy array selecting the right data type in NumPy directly affects memory usage, processing speed, and numerical accuracy. Using .dtype to check and modify data types helps manage in scientific computing and data analysis.

In [ ]:
array = np.array([1, 2, 3])
array.dtype

dtype('int64')

5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?



Ans in python ndarray means n-dimensial, is the fundamental data structure used to store and manipulate numerical data it is flexible but slower for numerical operations.An ndarray can represent data of any dimension (1D, 2D, 3D, etc.),
ndarray is homogenous in nature and python list hetrogenous in nature, in ndarrayBroad set of mathematical operations anfd in python list Limited requires libraries or custom functions

In [ ]:
array = np.array([1, 2, 3, 4])

In [ ]:
print(array)
print( array.dtype)

[1 2 3 4]
int64


In [ ]:
python_list = [1, 2, 3, 4]

In [ ]:
print(python_list)

[1, 2, 3, 4]


6.Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations



Ans.NumPy arrays offer significant performance advantages over Python lists, especially for large-scale numerical operations. This performance boost stems from several core features of ndarray in NumPy, including memory efficiency, optimized operations, and the ability to leverage low-level optimizations.

In [ ]:
size = 10
list1 = list(range(size))
list2 = list(range(size))

In [ ]:
list1
list2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
np_array1 = np.arange(size)
np_array2 = np.arange(size)


In [ ]:
np_array1
np_array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
output.



Ans.These functions are commonly used in data processing tasks where you need to combine data row-wise or column-wise.
vstacks arrays vertically,Same number of columns,Increases row count,
hstacks arrays horizontally	Same number of rows	Increases column count


In [ ]:
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])



In [ ]:
result_vstack = np.vstack((array1, array2))
print("Result of np.vstack:\n", result_vstack)


Result of np.vstack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
result_hstack = np.hstack((array1, array2))
print("Result of np.hstack:\n", result_hstack)

Result of np.hstack:
 [[1 2 5 6]
 [3 4 7 8]]


8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
array dimensions.



Ans.In NumPy, the fliplr() and flipud() methods are used to reverse arrays along specific axes, but they operate differently.\\
np.flipud() flips arrays along the vertical axis, changing the order of rows from top to bottom.
np.fliplr() flips arrays along the horizontal axis, changing the order of columns from left to right.


In [ ]:
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])


In [ ]:
result_fliplr = np.fliplr(array_2d)
print( array_2d)
print( result_fliplr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [ ]:
result_flipud = np.flipud(array_2d)
print( array_2d)
print( result_flipud)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[7 8 9]
 [4 5 6]
 [1 2 3]]


9.Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

Ans.array_split() is flexible, accommodating both even and uneven splits.
For uneven splits, the extra elements are added to the first few sub-arraysarray_split() is particularly useful when the number of elements doesn’t evenly divide by the number of sections, unlike split(), which requires even splits and will raise an error if not divisible.

In [ ]:
array = np.array([1, 2, 3, 4, 5,])
result = np.array_split(array, 3)
print( result)


[array([1, 2]), array([3, 4]), array([5])]


10.Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
operations?

Ans.Vectorization eliminates loops and takes advantage of optimized low-level code, improving speed and readability,vectorization and broadcasting allow NumPy to handle large datasets and complex computations efficiently, making it a powerful tool for scientific computing and data analysis,Broadcasting enables operations on arrays of differing shapes, saving memory and enhancing flexibility in array manipulations.


In [ ]:
array1 = np.array([1, 2, 3, 4])
array2 = np.array([5, 6, 7, 8])



In [ ]:
result = array1 + array2  #Vectorized addition
print(result)

[ 6  8 10 12]


In [ ]:
array = np.array([1, 2, 3])

In [ ]:
scalar = 1

In [ ]:
result = array + scalar
print(result)


[2 3 4]


11. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns

Ans.

In [ ]:
n=np.random.randn(3,3)


In [ ]:
n

array([[ 0.95094395, -0.36757011, -0.48256866],
       [-2.57368907, -1.75031926, -1.02970294],
       [-1.7240253 , -0.67772642,  0.03194867]])

In [ ]:
transposed_array = np.transpose(n)

In [ ]:
print( n)


[[ 0.95094395 -0.36757011 -0.48256866]
 [-2.57368907 -1.75031926 -1.02970294]
 [-1.7240253  -0.67772642  0.03194867]]


In [ ]:
print( transposed_array)


[[ 0.95094395 -2.57368907 -1.7240253 ]
 [-0.36757011 -1.75031926 -0.67772642]
 [-0.48256866 -1.02970294  0.03194867]]


12. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

Ans.

In [ ]:
one_d_array = np.arange(10)

In [ ]:
one_d_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
array_2x5 = one_d_array.reshape(2, 5)
array_2x5

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
array_5x2 = one_d_array.reshape(5, 2)
array_5x2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

13.Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array

Ans.

In [ ]:
random_float_array = np.random.rand(4, 4)

print(random_float_array)


[[0.56415129 0.52241106 0.44271919 0.67105066]
 [0.90667813 0.67331646 0.08057923 0.92030191]
 [0.24718291 0.6574386  0.0595778  0.57994216]
 [0.77928317 0.41320114 0.18466468 0.17392744]]


In [ ]:
bordered_array = np.pad(random_float_array, pad_width=1, mode='constant', constant_values=0)



In [ ]:
print("Original 4x4 Array:")
print(random_float_array)



Original 4x4 Array:
[[0.56415129 0.52241106 0.44271919 0.67105066]
 [0.90667813 0.67331646 0.08057923 0.92030191]
 [0.24718291 0.6574386  0.0595778  0.57994216]
 [0.77928317 0.41320114 0.18466468 0.17392744]]


In [ ]:
print("\n6x6 Array with Border of Zeros:")
print(bordered_array)


6x6 Array with Border of Zeros:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.56415129 0.52241106 0.44271919 0.67105066 0.        ]
 [0.         0.90667813 0.67331646 0.08057923 0.92030191 0.        ]
 [0.         0.24718291 0.6574386  0.0595778  0.57994216 0.        ]
 [0.         0.77928317 0.41320114 0.18466468 0.17392744 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


14.Using NumPy, create an array of integers from 10 to 60 with a step of 5



Ans.

In [ ]:
int_array = np.arange(10, 60, 5)


In [ ]:
int_array

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

15. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element

Ans.

In [ ]:
str_array = np.array(['python', 'numpy', 'pandas'])

In [ ]:
print(str_array)

['python' 'numpy' 'pandas']


In [ ]:
upper_case = np.char.upper(str_array)
upper_case

array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6')

In [ ]:
lower_case = np.char.lower(str_array)
lower_case

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [ ]:
title_case = np.char.title(str_array)
title_case

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

In [ ]:
capitalize_case = np.char.capitalize(str_array)
capitalize_case

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

16. Generate a NumPy array of words. Insert a space between each character of every word in the array.

Ans.

In [ ]:
words_array = np.array(['python', 'function', 'ayush', 'pwkills', 'life'])

In [ ]:
words_array

array(['python', 'function', 'ayush', 'pwkills', 'life'], dtype='<U8')

In [ ]:
spaced_words_array = np.char.join(' ', words_array)

In [ ]:
spaced_words_array

array(['p y t h o n', 'f u n c t i o n', 'a y u s h', 'p w k i l l s',
       'l i f e'], dtype='<U15')

17. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.#

Ans.

In [ ]:
array1 = np.array([[8, 7, 3],
                   [1, 5, 2],
                   [5, 4, 3]])


In [ ]:
array2 = np.array([[6, 5, 7],
                   [2, 8, 3],
                   [9, 1, 2]])

In [ ]:
array1

array([[8, 7, 3],
       [1, 5, 2],
       [5, 4, 3]])

In [ ]:
array2

array([[6, 5, 7],
       [2, 8, 3],
       [9, 1, 2]])

In [ ]:
array1+array2

array([[14, 12, 10],
       [ 3, 13,  5],
       [14,  5,  5]])

In [ ]:
array1-array2


array([[ 2,  2, -4],
       [-1, -3, -1],
       [-4,  3,  1]])

In [ ]:
array1*array2

array([[48, 35, 21],
       [ 2, 40,  6],
       [45,  4,  6]])

In [ ]:
array1/array2

array([[1.33333333, 1.4       , 0.42857143],
       [0.5       , 0.625     , 0.66666667],
       [0.55555556, 4.        , 1.5       ]])

18. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

Ans.

In [ ]:
identity_matrix = np.eye(5)
identity_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
diagonal_elements = np.diag(identity_matrix)

diagonal_elements

array([1., 1., 1., 1., 1.])

19. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array

Ans.

In [ ]:
random_integers = np.random.randint(0, 1001, size=100)

In [ ]:
random_integers

array([ 91, 767, 743, 261, 969, 849, 563, 327, 176, 270, 771, 893, 930,
       286, 294,  51, 383, 103, 877, 602, 821, 406, 104, 203, 304, 679,
       957, 868, 194, 650, 926, 642, 617, 273, 416, 395, 367, 390, 169,
       258, 690, 142, 954, 142, 494, 399, 305, 301, 526, 669, 411, 696,
       462, 485,  23, 855, 589, 745, 639, 873, 260, 398, 732, 302, 347,
       660, 290, 600, 196, 535, 802, 288, 861, 628, 137, 514, 743, 523,
       119, 300, 548, 261, 403, 740, 551, 728,  36, 379, 262,   5, 688,
        16,  42, 649, 146, 661, 558, 247, 272, 680])

In [ ]:
from sympy import isprime
prime_num = [num for num in random_integers if isprime(num)]

In [ ]:
prime_num

[743, 563, 383, 103, 877, 821, 617, 367, 23, 347, 137, 743, 523, 379, 5, 661]

In [ ]:
random_integers

array([ 91, 767, 743, 261, 969, 849, 563, 327, 176, 270, 771, 893, 930,
       286, 294,  51, 383, 103, 877, 602, 821, 406, 104, 203, 304, 679,
       957, 868, 194, 650, 926, 642, 617, 273, 416, 395, 367, 390, 169,
       258, 690, 142, 954, 142, 494, 399, 305, 301, 526, 669, 411, 696,
       462, 485,  23, 855, 589, 745, 639, 873, 260, 398, 732, 302, 347,
       660, 290, 600, 196, 535, 802, 288, 861, 628, 137, 514, 743, 523,
       119, 300, 548, 261, 403, 740, 551, 728,  36, 379, 262,   5, 688,
        16,  42, 649, 146, 661, 558, 247, 272, 680])

20.Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
averages.

Ans.

In [ ]:
daily_temperatures = np.random.uniform(5, 15, size=20)



In [ ]:
daily_temperatures

array([14.93144237,  8.68525664, 12.3973999 , 14.27328218,  6.62028869,
        8.59258764,  6.75287622, 14.07147904,  8.22880551,  5.9217833 ,
        8.31771238,  6.60410059,  8.41830057, 13.20333048,  5.4413401 ,
        6.12829515,  7.5456439 , 12.42788712,  9.73867492, 14.1096213 ])

In [ ]:
weekly_averages = np.mean(daily_temperatures[:20].reshape(-1, 5), axis=1)

In [ ]:
weekly_averages

array([11.38153396,  8.71350634,  8.39695682,  9.99002448])

In [ ]:
daily_temperatures

array([14.93144237,  8.68525664, 12.3973999 , 14.27328218,  6.62028869,
        8.59258764,  6.75287622, 14.07147904,  8.22880551,  5.9217833 ,
        8.31771238,  6.60410059,  8.41830057, 13.20333048,  5.4413401 ,
        6.12829515,  7.5456439 , 12.42788712,  9.73867492, 14.1096213 ])