1.Write a Python program to apply L1 regularization (Lasso) on a dataset using LogisticRegression(penalty='l1')
and print the model accuracy

In [3]:
from sklearn.datasets import load_iris

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [5]:
iris=load_iris()


In [8]:
x =iris.data
y=iris.target

In [10]:

iris_df = pd.DataFrame(data=x, columns=iris.feature_names)
iris_df['target'] = iris.target

In [11]:
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [12]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)


In [29]:
model = LogisticRegression(penalty='l1', solver='liblinear')  # Use 'liblinear' solver for L1
model.fit(X_train, y_train)

LogisticRegression(penalty='l1', solver='liblinear')

In [30]:
y_pred = model.predict(X_test)

In [31]:
y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [32]:
accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy with L1 Regularization: {accuracy}")

Model Accuracy with L1 Regularization: 1.0


2.Write a Python program to train Logistic Regression with L2 regularization (Ridge) using
LogisticRegression(penalty='l2'). Print model accuracy and coefficientsC

In [13]:
pd.DataFrame(iris_df)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [15]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)


In [16]:
model = LogisticRegression(penalty='l2')
model.fit(X_train, y_train)

LogisticRegression()

In [17]:
y_pred = model.predict(X_test)


In [18]:
y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [19]:
accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy with L2 Regularization: {accuracy}")

Model Accuracy with L2 Regularization: 1.0


In [20]:
print("Model Coefficients:")
print(model.coef_)

Model Coefficients:
[[-0.39340204  0.96258576 -2.37510761 -0.99874603]
 [ 0.50840364 -0.25486503 -0.21301366 -0.77575487]
 [-0.1150016  -0.70772072  2.58812127  1.77450091]]


3.Write a Python program to train Logistic Regression with Elastic Net Regularization (penalty='elasticnet')

In [21]:
iris = load_iris()
X = iris.data
y = iris.target

In [22]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [23]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [24]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [25]:
model = LogisticRegression(penalty='elasticnet', solver='saga', l1_ratio=0.5)
model.fit(X_train, y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


LogisticRegression(l1_ratio=0.5, penalty='elasticnet', solver='saga')

In [26]:
y_pred = model.predict(X_test)


In [27]:
y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [28]:
accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy with Elastic Net Regularization: {accuracy}")

Model Accuracy with Elastic Net Regularization: 1.0


In [29]:
print("Model Coefficients:")
print(model.coef_)

Model Coefficients:
[[ 0.51514265  1.77045245 -2.37360345 -0.80510964]
 [ 0.24035831  0.          0.         -0.64679323]
 [-1.29703928 -1.57042381  2.56497893  1.98833086]]


5.Write a Python program to train a Logistic Regression model for multiclass classification using
multi_class='ovr'C

In [34]:
from sklearn.datasets import make_classification # import make_classification from sklearn.datasets

x, y = make_classification(n_samples=1000, n_features=20, n_classes=3, random_state=42, n_informative=3)


In [35]:
x

array([[ 1.99615232,  0.21092616,  1.10317394, ...,  0.21486471,
         1.40220959,  1.00876251],
       [ 0.60073302,  0.14197991,  0.60826717, ...,  1.28920305,
         1.31060591, -1.48460479],
       [-1.97208903, -1.44392555, -0.94140317, ...,  1.49545825,
         0.84958453,  0.41156572],
       ...,
       [-0.96539616, -0.76548122,  1.89557477, ...,  1.37652266,
        -0.26382823,  0.17289168],
       [-0.63858583,  0.62308735, -0.99844085, ..., -2.15373057,
         0.97571338,  0.48630999],
       [ 0.62294403, -0.78703628,  0.23987275, ..., -1.07772075,
        -0.44664305, -0.50663483]])

In [36]:
y

array([2, 1, 0, 1, 1, 2, 0, 1, 2, 0, 1, 2, 0, 0, 0, 2, 0, 0, 1, 1, 2, 1,
       0, 1, 1, 1, 0, 2, 1, 1, 0, 0, 1, 0, 1, 0, 2, 2, 0, 2, 0, 0, 0, 1,
       2, 2, 1, 2, 1, 2, 0, 0, 1, 2, 2, 1, 0, 2, 2, 1, 0, 0, 1, 2, 2, 0,
       2, 2, 1, 2, 2, 2, 1, 2, 1, 0, 1, 1, 2, 1, 1, 0, 1, 2, 2, 1, 2, 1,
       1, 2, 2, 2, 2, 2, 2, 0, 0, 2, 1, 1, 1, 0, 1, 1, 1, 2, 2, 0, 0, 0,
       0, 0, 1, 2, 0, 0, 0, 1, 0, 1, 1, 2, 1, 0, 2, 1, 0, 2, 1, 0, 1, 0,
       1, 2, 2, 0, 0, 1, 2, 0, 2, 0, 0, 2, 0, 0, 0, 0, 0, 2, 2, 1, 1, 2,
       0, 0, 1, 0, 0, 2, 2, 2, 0, 0, 2, 1, 2, 1, 1, 1, 2, 2, 0, 0, 2, 0,
       1, 0, 1, 2, 2, 2, 2, 1, 0, 0, 2, 2, 0, 1, 0, 1, 0, 1, 2, 1, 2, 0,
       0, 2, 2, 1, 1, 0, 1, 0, 1, 0, 1, 2, 1, 1, 0, 2, 0, 2, 1, 0, 2, 2,
       2, 0, 0, 1, 1, 2, 1, 1, 1, 0, 0, 2, 0, 1, 2, 1, 1, 1, 1, 0, 0, 2,
       2, 0, 2, 0, 0, 2, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 2, 1, 1, 1, 1, 1,
       2, 2, 0, 2, 2, 0, 1, 0, 2, 0, 1, 2, 2, 1, 1, 0, 1, 2, 2, 0, 2, 0,
       2, 0, 0, 1, 1, 0, 1, 1, 1, 2, 0, 0, 0, 0, 1,

In [38]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)


In [39]:
model = LogisticRegression(multi_class='ovr')
model.fit(X_train, y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


LogisticRegression(multi_class='ovr')

In [40]:
y_pred = model.predict(X_test)

In [41]:
y_pred

array([0, 0, 0, 0, 2, 0, 2, 2, 2, 1, 0, 0, 1, 2, 2, 2, 2, 0, 2, 2, 0, 2,
       1, 2, 0, 1, 1, 1, 0, 1, 0, 1, 2, 0, 0, 1, 2, 0, 2, 0, 2, 0, 0, 1,
       0, 0, 0, 2, 1, 2, 1, 0, 2, 1, 1, 0, 0, 0, 0, 0, 0, 2, 1, 2, 0, 2,
       2, 0, 2, 2, 0, 2, 2, 0, 0, 2, 2, 2, 1, 2, 2, 2, 0, 1, 0, 1, 0, 1,
       2, 0, 2, 2, 0, 0, 1, 0, 2, 0, 2, 0, 2, 0, 0, 0, 2, 2, 2, 2, 0, 2,
       2, 1, 2, 0, 1, 2, 0, 2, 1, 1, 2, 1, 0, 1, 0, 1, 0, 2, 1, 2, 0, 1,
       2, 2, 0, 0, 0, 2, 0, 1, 2, 2, 2, 2, 0, 2, 2, 2, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 2, 2, 0, 2, 2, 2, 0, 0, 0, 0, 2, 1, 0, 0, 0, 2, 2,
       1, 2, 1, 0, 2, 0, 2, 2, 1, 1, 1, 2, 0, 0, 0, 1, 0, 1, 2, 0, 2, 0,
       2, 0])

In [42]:
accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy with multi_class='ovr': {accuracy}")


Model Accuracy with multi_class='ovr': 0.625


6.Write a Python program to apply GridSearchCV to tune the hyperparameters (C and penalty) of Logistic
Regression. Print the best parameters and accuracyC

In [43]:
iris = load_iris()
X = iris.data
y = iris.target

In [44]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [45]:
param_grid = {
    'C': [0.1, 1, 10, 100],
    'penalty': ['l1', 'l2']
}

In [46]:
model = LogisticRegression()


In [48]:
from sklearn.model_selection import train_test_split, GridSearchCV

grid_search = GridSearchCV(model, param_grid, cv=5, scoring='accuracy')

In [49]:
grid_search

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [0.1, 1, 10, 100], 'penalty': ['l1', 'l2']},
             scoring='accuracy')

In [50]:
grid_search.fit(X_train, y_train)


/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [0.1, 1, 10, 100], 'penalty': ['l1', 'l2']},
             scoring='accuracy')

In [51]:
print("Best Hyperparameters:", grid_search.best_params_)
print("Best Accuracy:", grid_search.best_score_)

Best Hyperparameters: {'C': 1, 'penalty': 'l2'}
Best Accuracy: 0.9666666666666666


7.Write a Python program to evaluate Logistic Regression using Stratified K-Fold Cross-Validation. Print the
average accuracy.

In [53]:
from sklearn.model_selection import StratifiedKFold

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

In [54]:
accuracy_scores = []

In [55]:
for train_index, test_index in skf.split(X, y):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]

In [57]:
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [58]:
y_pred = model.predict(X_test)

In [59]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 2,
       2, 1, 2, 2, 2, 2, 2, 2])

In [60]:
accuracy = accuracy_score(y_test, y_pred)
accuracy_scores.append(accuracy)


In [61]:
average_accuracy = sum(accuracy_scores) / len(accuracy_scores)
print(f"Average Accuracy using Stratified K-Fold Cross-Validation: {average_accuracy}")


Average Accuracy using Stratified K-Fold Cross-Validation: 0.9333333333333333


8.Write a Python program to load a dataset from a CSV file, apply Logistic Regression, and evaluate its
accuracy.

In [62]:
data = pd.read_csv('amazon.csv')

In [63]:
data.head(2)

product_id                                       product_name  \
0  B07JW9H4J1  Wayona Nylon Braided USB to Lightning Fast Cha...   
1  B098NS6PVG  Ambrane Unbreakable 60W / 3A Fast Charging 1.5...   

                                            category discounted_price  \
0  Computers&Accessories|Accessories&Peripherals|...             ₹399   
1  Computers&Accessories|Accessories&Peripherals|...             ₹199   

  actual_price discount_percentage rating rating_count  \
0       ₹1,099                 64%    4.2       24,269   
1         ₹349                 43%    4.0       43,994   

                                       about_product  \
0  High Compatibility : Compatible With iPhone 12...   
1  Compatible with all Type C enabled devices, be...   

                                             user_id  \
0  AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...   
1  AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...   

                                           user_name  \
0  Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...   
1  ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...   

                                           review_id  \
0  R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...   
1  RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...   

                                        review_title  \
0  Satisfied,Charging is really fast,Value for mo...   
1  A Good Braided Cable for Your Type C Device,Go...   

                                      review_content  \
0  Looks durable Charging is fine tooNo complains...   
1  I ordered this cable to connect my phone to An...   

                                            img_link  \
0  https://m.media-amazon.com/images/W/WEBP_40237...   
1  https://m.media-amazon.com/images/W/WEBP_40237...   

                                        product_link  
0  https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...  
1  https://www.amazon.in/Ambrane-Unbreakable-Char...

In [75]:

X = data.drop('rating', axis=1) # Drop the target column to get features
y = data['rating']

In [77]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()


In [78]:
for column in X.select_dtypes(include=['object']).columns:
    X[column] = label_encoder.fit_transform(X[column])

In [79]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [80]:
model = LogisticRegression(max_iter=1000)  # Increase max_iter if needed
model.fit(X_train, y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(max_iter=1000)

In [81]:
y_pred = model.predict(X_test)


In [82]:
y_pred

array(['4.3', '4.2', '4.2', '4.3', '4.1', '4.2', '4.2', '4.1', '4.0',
       '4.1', '4.2', '4.3', '4.2', '4.3', '4.2', '4.3', '4', '4.0', '4.4',
       '4.2', '3.0', '4.2', '4.1', '4.2', '4.2', '4.0', '4.1', '3.9',
       '4.1', '4.2', '3.8', '4.2', '3', '4.2', '4.2', '4.3', '3.8', '|',
       '4.1', '3.9', '3.8', '4.3', '4.2', '3.9', '4.1', '4.2', '4', '4.1',
       '3.3', '4', '4.3', '4.3', '4.1', '4.3', '4.2', '4.1', '4.2', '4.1',
       '4.1', '4.1', '4.2', '4.1', '4.4', '4.2', '4.2', '4.0', '2', '4.4',
       '4.2', '4.2', '4.1', '4.2', '4.2', '4.2', '4.0', '4.1', '4.2',
       '4.2', '4.2', '4.2', '4.1', '4.2', '4.1', '4.1', '4.1', '4.1',
       '4.1', '4.0', '4.0', '4.0', '4.2', '4.1', '4.2', '4.1', '4.1',
       '4.1', '4.1', '4.1', '4.1', '4.3', '3.9', '4.1', '4.1', '4.1',
       '4.1', '4.3', '4.0', '4.1', '4.2', '4.2', '4.0', '4.3', '4.2',
       '4.1', '4.0', '4.3', '3.9', '4.0', '4.1', '4.2', '4.1', '4.1',
       '4.3', '4.2', '4.3', '4.1', '4.1', '4.1', '4.0', '4.1', '4.1

In [83]:
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

Accuracy: 0.24232081911262798


9. Write a Python program to apply RandomizedSearchCV for tuning hyperparameters (C, penalty, solver) in
Logistic Regression. Print the best parameters and accuracy.

In [85]:
import numpy as np
param_dist = {
    'C': np.logspace(-4, 4, 20),  # Values for C (logarithmic scale)
    'penalty': ['l1', 'l2'],  # Values for penalty
    'solver': ['liblinear', 'saga']  }

In [86]:
model = LogisticRegression()


In [88]:
from sklearn.model_selection import train_test_split, RandomizedSearchCV

random_search = RandomizedSearchCV(
    model, param_distributions=param_dist, n_iter=10, cv=5, scoring='accuracy', random_state=42
)

In [89]:
random_search.fit(X_train, y_train)


/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_split.py:805: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter wa

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': array([1.00000000e-04, 2.63665090e-04, 6.95192796e-04, 1.83298071e-03,
       4.83293024e-03, 1.27427499e-02, 3.35981829e-02, 8.85866790e-02,
       2.33572147e-01, 6.15848211e-01, 1.62377674e+00, 4.28133240e+00,
       1.12883789e+01, 2.97635144e+01, 7.84759970e+01, 2.06913808e+02,
       5.45559478e+02, 1.43844989e+03, 3.79269019e+03, 1.00000000e+04]),
                                        'penalty': ['l1', 'l2'],
                                        'solver': ['liblinear', 'saga']},
                   random_state=42, scoring='accuracy')

In [90]:
print("Best Hyperparameters:", random_search.best_params_)
print("Best Accuracy:", random_search.best_score_)


Best Hyperparameters: {'solver': 'liblinear', 'penalty': 'l1', 'C': 0.08858667904100823}
Best Accuracy: 0.18857610474631753
